name: Eslint

on:
  push:
    branches: [ $main, $dev ]
  pull_request:
    branches: [ $main, $dev ]

jobs:
  run-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm i

      - name: Run linter
        run: npm run lint
